SELECT POLICY_NUM,JOB_NUM,PATTERN_CODE,TRUNC(MBUPDATETIME),PREMIUM_AMT,ETL_PROCESS_TS,GL_RECORD_STATUS
FROM CSP_PROPERTY_TRANSACTION WHERE POLICY_NUM='4050038983';


SELECT POLICY_NUM,JOB_NUM,PATTERN_CODE,TRUNC(MBUPDATETIME),PREMIUM_AMT,ETL_PROCESS_TS,GL_RECORD_STATUS
FROM CSP_PROPERTY_TRANSACTION WHERE POLICY_NUM='4050037758';



SELECT POLICY_NUM,JOB_NUM,PATTERN_CODE,SUM(PREMIUM_AMT),ETL_PROCESS_TS
FROM CSP_PROPERTY_TRANSACTION WHERE POLICY_NUM='4050037758' GROUP BY POLICY_NUM, JOB_NUM, PATTERN_CODE, ETL_PROCESS_TS;
